#!/usr/bin/env python

# Author: Florin Baca
# Date: July 2013

import sys, tarfile, os, time

CONF = 'backup.conf'

# Parse the config file. We are mainly
# interested to drop comments and blank
# lines.

def parseConfig(loc=CONF):
	try:
		file = open(loc, 'r')
		data = file.readlines()
		file.close()
	except:
		print "Unable to open config file: %s\nPlease retry with a valid config file." % loc
		sys.exit(1)
	conf = {}
	for line in data:
		if ((not line.startswith('#') and line != '\n')):
			line = line.replace('\n', '')
			param = line.split('=')[0]
			values = line.split('=')[1:]
			if ',' in values:
				values = values[0].split()
			conf[param] = values

	return conf

def archiveFiles(dest, name, source=[]):
	if not '.tar.gz' in name:
		name = str(name) + '.tar.gz'
	dest = str(dest) + '/' + str(name)
	if not os.path.isfile(dest):
		tarFile = tarfile.open(dest, 'w:gz')
		for path in source:
			print "Adding %s to %s" % (path, name)
			init = time.time()
			tarFile.add(path)
			end = time.time() - init
			print "Finished in %.2f" % end
		tarFile.close()
	else:
		print "%s already exists, please retry." % dest

def fileName():
	name = 'pyBackup' + str(time.strftime('%d%m%Y%H%M%S', time.localtime()))
	return name

def main():
	params = parseConfig()
	print params
	dest = params['destination'][0]
	source = params['source']
	name = fileName()
	archiveFiles(dest, name, source)

if __name__ == '__main__':
	main()
